apiVersion: v1
kind: Service
metadata:
  name: '{{aplication_name}}-service'
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{aplication_name}}
    version: '{{app_image_version}}'