server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://elasticsearch-node-01:9200"]
monitoring.ui.container.elasticsearch.enabled: true
xpack:
  apm.ui.enabled: false
  graph.enabled: false
  ml.enabled: false
  monitoring.enabled: false
  reporting.enabled: false
  security.enabled: false
  grokdebugger.enabled: false
  searchprofiler.enabled: false
