--- 
- name: "部署应用"
  shell: 'kubectl apply -f .'
  args: /tmp/{{source_dir}}
  when:  step== 'release'
- name: '更新应用' 
  shell: 'kubectl apply -f deployment.yml && kubectl  roolout pause deployment/{{app_name}}'
  when: step == 'update'
- name: '上线应用' 
  shell: 'kubectl apply -f deployment.yml && kubectl  roolout pause deployment/{{app_name}}'
  when: step == 'online'